// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath PluginDependencies.buildGradle
        classpath PluginDependencies.kotlinGradle
        classpath PluginDependencies.googleServices
        classpath PluginDependencies.hilt
        classpath PluginDependencies.firebaseCrashlytics
        classpath libs.com.google.devtools.ksp.gradle.plugin
        classpath PluginDependencies.androidToolsR8
        classpath PluginDependencies.firebasePerf
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url PluginDependencies.jitPackIo }
        maven { url PluginDependencies.artifactory }
        maven { url PluginDependencies.talsecRepositories }
    }
}