object Versions {
    const val kotlin = "1.6.10"
    const val coreKtx = "1.10.1"
    const val appCompat = "1.6.1"
    const val constraintLayout = "2.1.4"
    const val legacySupport = "1.0.0"
    const val testJunit = "1.1.5"
    const val testImplJunit = "4.13.2"
    const val testEspresso = "3.5.1"
    const val espressoIdling = "3.4.0"
    const val material = "1.9.0"
    const val biometric = "1.2.0-alpha05"
    const val workRuntime = "2.8.1"
    const val playServicesVision = "20.1.3"
    const val playServicesMaps = "18.1.0"
    const val playServicesLocation = "21.0.1"
    const val playServicesMapsUtils = "2.3.0"
    const val barcode = "17.2.0"
    const val smsRetrieve = "18.0.1"
    const val inAppUpdate = "1.8.1"
    const val paper = "2.7.1"
    const val coroutinesCore = "1.7.1"
    const val coroutinesAndroid = "1.7.1"
    const val lottie = "5.2.0"

    const val liveDataKtx = "2.6.1"
    const val lifeCycleExtension = "2.2.0"
    const val wearable = "2.9.0"
    const val lifeCycleCompiler = "2.6.1"

    const val roomRuntime = "2.6.0-rc01"
    const val roomKtx = "2.6.0-rc01"
    const val roomCompiler = "2.6.0-rc01"

    const val navigationFragment = "2.7.4"
    const val navigationUi = "2.7.4"
    const val navigationKtx = "1.6.1"

    const val coil = "2.4.0"
    const val picasso = "2.8"
    const val videoCache = "2.7.1"

    const val glide = "4.15.1"
    const val glideCompiler = "4.14.2"
    const val hiltAndroid = "2.44"
    const val hiltCompiler = "2.44"
    const val sharedPref = "1.2.1"
    const val circleImageView = "3.1.0"
    const val expandableLayout = "2.9.2"

    const val camera = "1.3.0-alpha02"
    const val cameraLifecycle = "1.3.0-alpha02"
    const val cameraView = "1.3.0-alpha02"

    const val firebaseBom = "26.6.0"
    const val firebaseStorage = "20.2.1"
    const val firebaseFireStore = "24.8.1"
    const val firebaseMessaging = "23.2.1"

    const val retrofit = "2.9.0"
    const val retrofitConverter = "2.9.0"
    const val okhttp = "4.10.0"
    const val okhttpLogging = "4.10.0"
    const val gson = "2.10"
    const val viewModelKoin = "2.0.1"
    const val libMaterialProgress = "1.7"
    const val smartRefreshLayout = "1.1.2"
    const val smartRefreshHeader = "1.1.2"
    const val skeleton = "1.1.2"
    const val shimmerLayout = "2.1.0"
    const val facebookShimmer = "0.5.0@aar"
    const val chuckerLib = "3.5.2"
    const val chuckerLibNoOp = "3.5.2"
    const val ticker = "2.0.2"
    const val ktorAndroid = "2.1.2"
    const val kotlinxCoroutines = "1.7.1"

    const val mlkitFaceDetection = "17.1.0"
    const val mlkitTextRecognition = "19.0.0"
    const val mlkitBarcodeScanning = "18.3.0"

    const val lifecycleViewModel = "2.6.1"
    const val lifecycleRuntime = "2.6.1"
    const val splashScreen = "1.0.1"
    const val securityCrypto = "1.1.0-alpha06"
    const val playServiceVisionCommon = "19.1.3"
    const val playServiceVision = "20.1.3"
    const val rxBinding = "4.0.0"
    const val viewPagerDotIndicator = "4.1.2"
    const val pageTransformerHelper = "v1.0.1"
    const val rvAnimators = "4.0.2"
    const val qrGenAndroid = "2.6.0"
    const val customQrGenerator = "2.0.0-alpha01"
    const val commonsLang = "3.12.0"
    const val animatedProgressBar = "0.1.0"
    const val rxRelay = "2.1.1"
    const val databinding = "8.0.2"
    const val tensorFlow = "2.9.0"
    const val xenione = "1.0.0"
    const val flexbox = "3.0.0"
}