package uz.fido.utils.const

object Const {

    const val TOTAL_BALANCE = "total_balance"
    const val TOTAL_BALANCE_UPDATED_AT = "total_balance_updated_on"

    /*PAYMENT */
    const val DB_HELPER_VERSION = 1

    const val APP_THEME = "app_theme"
    const val USER_QWERTY_KEY = "user_qwerty_key"
    const val FAST_ACCESS = "fast_access"
    const val UPDATE_FAST_ACCESS = "UPDATE_FAST_ACCESS"
    const val MAIN_WIDGETS_VERSION_SAVED = "main_widget_version_saved"
    const val UPDATE_MAIN_WIDGETS = "false"
    const val MAIN_WIDGETS = "main_widgets"
    const val MAIN_WIDGETS_VERSION = 5
    const val TOTAL_BALANCE_TYPE = "balance_type"
    const val PAPER_CLIENT_TOKEN = "client_token"
    const val PAPER_PAYMENT_VERSION = "payment_version"
    const val PAPER_PAYMENT_VERSION_DB = "payment_version_db"
    const val PAPER_CLIENT_INFO = "client_info"
    const val PAPER_CLIENT_PHONE = "client_phone"
    const val PAPER_CLIENT_ID = "client_id"
    const val PAPER_CLIENT_FULL_NAME = "client_full_name"
    const val PAPER_FCM_TOKEN = "fcm_token"
    const val PAPER_CLIENT_POINTS = "client_points"
    const val PAPER_CLIENT_STATUS_NAME = "client_status_name"
    const val PAPER_CLIENT_STATUS_ID = "client_status_id"
    const val PAPER_CLIENT_APPLICATION_COUNT = "application_count"
    const val PAPER_USER_PHOTO_PATH = "user_photo_path"
    const val APPLICATION_COUNT = "APPLICATION_COUNT"
    const val FINGER_STATE = "fingerprint_state"
    const val PAPER_CLIENT_PIN = "client_pin"
    const val PAPER_CARDS_WITH_BALANCE_VIS = "client_cards_with_balance_visibility"
    const val PAPER_CLIENT_CARDS = "client_cards"
    const val BALANCE_VISIBILITY = "hide_balance"
    const val PAPER_PAYMENT_PIN_CONFIRMATION = "payment_pin_confirmation"
    const val USER_LOGGED = "logged"
    const val DEVICE_CODE = "device_code"
    const val APP_LANGUAGE = "language"
    const val PHONE_NUMBER = "phone_number"
    const val CARD_NUMBER = "card_number"
    const val EMAIL = "email"
    const val OPERATION = "operation_main"
    const val ADD_CARD_OPERATION = "add_card_operation"
    const val OPERATION_AMOUNT = "operation_amount"
    const val OPERATION_CURRENCY = "SUCCESS_CURRENCY"
    const val SENDER_CARD = "SENDER_CARD"
    const val RECEIVER_CARD = "RECEIVER_CARD"
    const val PAYMENT_SERVICE = "EXTRA_PAYMENT_SERVICE"
    const val PAYMENT_KEY_VALUES = "key_values"
    const val EXTRA_PARAMS = "EXTRA_PAYMENT_PARAMS"
    const val TRANSACTION_ID = "transactId"
    const val RANDOM_TEXT = "random_text"
    const val QR_PAYMENT = "QR_PAYMENT"
    const val ORDER_CARD = "order_card"
    const val LAYOUT_MANAGER_GRID = "LAYOUT_MANAGER_GRID"
    const val CARD = "card"
    const val USER_NAME = "USER_NAME"
    const val FIRST_NAME = "FIRST_NAME"
    const val LAST_NAME = "LAST_NAME"
    const val PATRONYMIC = "PATRONYMIC"
    const val USER_FULL_NAME = "USER_FULL_NAME"
    const val USER_BIRTHDAY = "USER_BIRTHDAY"
    const val USER_CITIZENSHIP = "USER_CITIZENSHIP"
    const val USER_PASSWORD_DATA = "USER_PASSWORD_DATA"
    const val USER_PASS_EXPIRE_DATE = "USER_PASS_EXPIRE_DATE"
    const val USER_PASS_GIVEN_DATE = "USER_PASS_GIVEN_DATE"
    const val USER_PINFL = "USER_PINFL"
    const val USER_IDENTIFIED = "USER_IDENTIFIED"
    const val TEMPLATE_TYPE_1 = "TEMPLATE"
    const val TEMPLATE_TYPE_2 = "AUTO_PAYMENT"
    const val TYPE_LOAN = "TYPE_LOAN"
    const val TYPE_DEPOSIT = "TYPE_DEPOSIT"
    const val SEARCH_LIST = "SEARCH_LIST"
    const val STRING_LINE = "STRING_LINE"
    const val PASSWORD_ENC = "ENC_PASS"
    const val KEY_K = "KEY_K"

    var request_id = ""

    const val PLAY_MARKET = "https://play.google.com/store/apps/details?id=uz.fido.universaldigital"
}