plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
}

android {

    namespace 'uz.fido.network'

    defaultConfig {
        minSdkVersion ConfigData.MIN_SDK_VERSION
        compileSdk ConfigData.COMPILE_SDK_VERSION
        targetSdkVersion ConfigData.TARGET_SDK_VERSION
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        externalNativeBuild {
            cmake {
                cppFlags("")
            }
        }
    }
    buildFeatures {
        buildConfig true
    }
    externalNativeBuild {
        cmake {
            path = "src/main/cpp/CMakeLists.txt"
            version = "3.22.1"
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation(libs.com.google.dagger.hilt.android)
    kapt libs.com.google.dagger.hilt.android.compiler

    implementation(libs.com.squareup.retrofit2.retrofit)
    implementation(libs.com.squareup.retrofit2.converter.gson)
    implementation(libs.com.google.code.gson)
    implementation(libs.androidx.room.room.runtime)
    kapt libs.androidx.room.room.compiler

    implementation(libs.androidx.room.room.ktx)
    implementation(libs.io.github.pilgr.paperdb)
    implementation(libs.com.squareup.okhttp3)
    implementation(libs.com.squareup.okhttp3.logging.interceptor)

    implementation(project(ModuleList.UTILS))

}