-keepattributes *Annotation*
-keep class kotlin.Metadata { *; }
-keepclassmembers class kotlin.Metadata { *; }
-keep class com.google.gson.** { *; }
-keep class uz.fido.network.domain.model.** { *; }
-keep class uz.fido.network.di.**{*;}
-keep class uz.myid.android.sdk.**{*;}
-dontwarn kotlin.time.**