package uz.fido.network.domain.model.loans.loan_groups

import java.io.Serializable

data class CreditGroup(
    val activeDate: String,
    val creditType: String,
    val currencyСode: String,
    val deactivDate: String,
    val description: String,
    val formDelivery: String,
    val formRedemption: String,
    val gracePeriodMax: String,
    val gracePeriodMin: String,
    val groupId: String,
    val pfGroupName: String,
    val initialPercentMax: String,
    val initialPercentMin: String,
    val loanAccount: String,
    val maxSumma: String,
    val minSumma: String,
    val name: String,
    val onOf: String,
    val percentMax: String,
    val percentMaxPd: String,
    val percentMin: String,
    val percentMinPd: String,
    val pfProductId: String,
    val purposeLoan: String,
    val security: String,
    val status: String,
    val time_max: String,
    val time_min: String,
    var monthlyAmount: String? = null,
    var creditAmount: String? = null,
    var selectedDate: String? = null,
    var selectedPercent: String? = null,
    var insuranceAmount: String? = null,
    var paymentDate: String? = null,
    var ccId: String? = null
) : Serializable