package uz.fido.network.domain.model.loans.loan_groups

data class CreditProduct(
    val activeDate: String,
    val creditType: String,
    val currencyCode: String,
    val deactivDate: String,
    val description: String,
    val formDelivery: String,
    val formRedemption: String,
    val gracePeriodMax: String,
    val gracePeriodMin: String,
    val groupId: Int,
    val groupName: String,
    val initialPercentMax: Int,
    val initialPercentMin: Int,
    val maxSumma: Long,
    val minSumma: Int,
    val name: String,
    val onOf: String,
    val percentMax: Int,
    val percentMaxPd: String,
    val percentMin: Int,
    val percentMinPd: String,
    val productId: Int,
    val purposeLoan: String,
    val status: String,
    val time_max: String,
    val time_min: String,
    var amount: String = ""
) : java.io.Serializable