plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.devtools.ksp'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id 'dagger.hilt.android.plugin'
    id 'com.google.firebase.firebase-perf'
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    namespace ConfigData.APPLICATION_ID
    defaultConfig {
        applicationId ConfigData.APPLICATION_ID
        minSdkVersion ConfigData.MIN_SDK_VERSION
        compileSdk ConfigData.COMPILE_SDK_VERSION
        targetSdkVersion ConfigData.TARGET_SDK_VERSION
        versionCode ConfigData.VERSION_CODE
        versionName ConfigData.RELEASE_VERSION_NAME
        archivesBaseName = ConfigData.ARCHIVES_BASE_NAME
        vectorDrawables.useSupportLibrary true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags("")
            }
        }
    }
    buildFeatures {
        buildConfig true
        viewBinding true
    }

    signingConfigs {
        production {
            v1SigningEnabled true
            v2SigningEnabled true
            enableV3Signing = true
            enableV4Signing = true
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            ndk {
                //noinspection ChromeOsAbiSupport
                abiFilters "arm64-v8a", "armeabi-v7a"
            }
            signingConfig signingConfigs.production
        }
    }
    externalNativeBuild {
        cmake {
            path = "src/main/cpp/CMakeLists.txt"
            version = "3.22.1"
        }
    }
    bundle {
        language {
            enableSplit = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11

    }
    kotlinOptions {
        jvmTarget = '11'
    }
    ndkVersion '25.0.8775105'
    packagingOptions {
        pickFirst 'lib/armeabi-v7a/liblog.so'
        pickFirst 'lib/arm64-v8a/liblog.so'
        pickFirst 'lib/x86/liblog.so'
        pickFirst 'lib/x86_64/liblog.so'
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    implementation(libs.kotlinx.metadata.jvm)
    implementation(libs.androidx.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.livedata.ktx)
    implementation(libs.androidx.work.runtime)
    implementation(libs.androidx.legacy.support)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.navigation.ui.ktx)
    implementation(libs.androidx.navigation.fragment.ktx)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.androidx.lifecycle.extensions)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.camera.camera2)
    implementation(libs.androidx.camera.camera.lifecycle)
    implementation(libs.androidx.camera.camera.view)
    implementation(libs.androidx.security.crypto)
    implementation(libs.androidx.biometric)
    implementation(libs.androidx.preference)

    implementation(libs.com.google.android.material)
    implementation(libs.com.google.android.play.services.maps)
    implementation(libs.com.google.android.play.services.vision)
    implementation(libs.com.google.android.play.services.vision.common)
    implementation(libs.com.google.android.play.services.location)
    implementation(libs.com.google.android.play.services.auth.api.phone)
    implementation(libs.com.google.android.play.services.mlkit.face.detection)
    implementation(libs.com.google.android.play.services.mlkit.text.recognition)
    implementation(libs.com.google.android.play.services.mlkit.barcode.scanning)
    implementation(libs.com.google.android.flexbox)
    implementation(libs.com.google.android.app.update)
    implementation(libs.com.google.dagger.hilt.android)
    implementation(libs.com.google.mlkit.barcode.scanning)
    implementation(libs.com.google.code.gson)
    implementation(libs.com.google.maps.utils)
    implementation libs.firebase.database.ktx

    ksp(libs.com.google.dagger.hilt.android.compiler)
    compileOnly(libs.com.google.android.wearable)

    implementation(libs.org.jetbrains.kotlin)
    implementation(libs.org.jetbrains.coroutines.core)
    implementation(libs.org.jetbrains.coroutines.android)
    implementation(libs.org.jetbrains.kotlin.reflect)

    implementation(platform(libs.com.google.firebase.firebase.bom))
    implementation(libs.com.google.firebase.firebase.analytics.ktx)
    implementation(libs.com.google.firebase.firebase.storage)
    implementation(libs.com.google.firebase.firebase.crashlytics)
    implementation(libs.com.google.firebase.firebase.dynamic.links.ktx)
    implementation(libs.com.google.firebase.firebase.messaging.ktx)
    implementation(libs.com.google.firebase.firebase.firestore.ktx)
    implementation(libs.com.google.firebase.firebase.perf)
    implementation(libs.com.bumptech.glide)

    //retrofit
    implementation(libs.com.squareup.retrofit2.retrofit)
    implementation(libs.com.squareup.retrofit2.converter.gson)
    implementation(libs.com.squareup.okhttp3.logging.interceptor)

    //coil,picasso (image loader)
    implementation(libs.io.coil.kt.coil)
    implementation(libs.com.squareup.picasso.picasso)

    implementation(libs.de.hdodenhof.circleimageview)
    implementation(libs.com.github.cachapa.expandableLayout)

    implementation(libs.org.koin.koin.androidx.viewmodel)
    implementation(libs.com.redmadrobot.input.mask.android)
    implementation(libs.com.robinhood.ticker.ticker)
    implementation(libs.io.ktor.ktor.client.android)
    implementation(libs.com.jakewharton.rxbinding4.rxbinding)
    implementation(libs.com.tbuonomo.andrui.viewpagerdotsindicator)
    implementation(libs.com.github.alexzhirkevich.custom.qr.generator)
    implementation(libs.org.apache.commons.commons.lang3)
    implementation(libs.com.github.mckrpk.animatedProgressBar)
    implementation(libs.com.jakewharton.rxrelay2.rxrelay)
    implementation(libs.io.github.pilgr.paperdb)

    implementation(libs.io.supercharge.shimmerlayout)
    implementation(libs.com.airbnb.android.lottie)
    implementation(libs.com.github.philjay.mpadroidChart)
    implementation(libs.uz.myid.sdk.capture)
    implementation(libs.talsec.rasp)

    implementation(files(ModuleList.NFC_LIBRARY))
    implementation(project(ModuleList.CARD_SCANNER))
    implementation(project(ModuleList.NETWORK))
    implementation(project(ModuleList.UTILS))

}
