apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'


android {

    defaultConfig {
        minSdkVersion ConfigData.minSdkVersion
        compileSdk ConfigData.compileSdkVersion
        targetSdkVersion ConfigData.targetSdkVersion
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'proguard-rules-keep-lib.pro'
    }

    externalNativeBuild {
        cmake { path "src/main/cpp/CMakeLists.txt" }
    }

    buildTypes {
        release {
            minifyEnabled false
            consumerProguardFiles 'proguard-rules-keep-lib.pro'
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules-keep-lib.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    ndkVersion '25.0.8775105'
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation ProjectDependencies.coreKtx
    implementation ProjectDependencies.appCompat
    implementation ProjectDependencies.espressoIdling
    implementation ProjectDependencies.constraintLayout
    implementation ProjectDependencies.tensorFlow
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = "com.github.yusufbekibragimov"
                artifactId = "cardscan-base"
                version = "1.2"
            }
        }
    }
}
