apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'


android {
    namespace 'uz.fido.cardScanner'
    defaultConfig {
        minSdkVersion ConfigData.MIN_SDK_VERSION
        compileSdk ConfigData.COMPILE_SDK_VERSION
        targetSdkVersion ConfigData.TARGET_SDK_VERSION
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'proguard-rules-keep-lib.pro'
    }

    externalNativeBuild {
        cmake {
            path = "src/main/cpp/CMakeLists.txt"
            version = "3.22.1"
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            consumerProguardFiles 'proguard-rules-keep-lib.pro'
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules-keep-lib.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(libs.androidx.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.test.espresso.espresso.idling.resource)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.org.tensorflow.tensorflow.lite)
}
