package uz.fido.network.domain.model.loans.loan_products

import com.google.gson.annotations.SerializedName
import java.io.Serializable

data class CreditProduct(
    val productName: String? = null,
    val loan3: String? = null,
    val filialName: String? = null,
    var amount: String? = null,
    @SerializedName(value = "percent ", alternate = ["percent"])
    val percent: String? = "0",
    val loanId: String? = "null",
    val loan1: String? = null,
    val loanContractId: String? = null,
    val contractCode: String? = null,
    val mainAccBalance: String? = null,
    val closeDate: String? = null,
    val loan7: String? = null,
    val codeFilial: String? = null,
    val guarType: ArrayList<GuarType>? = arrayListOf(),
    @SerializedName(value = "accruedOverDueInterest ", alternate = ["accruedOverDueInterest"])
    val accruedOverDueInterest: String? = "0",
    val loan5: String? = null,
    val loan2: String? = null,
    val loan22: String? = null,
    val productId: Int? = null,
    @SerializedName(value = "overdueDebt ", alternate = ["overdueDebt"])
    val overdueDebt: String? = "0",
    @SerializedName(value = "arrearsOnPrincipal ", alternate = ["arrearsOnPrincipal"])
    val arrearsOnPrincipal: String? = "0",
    val contractDate: String? = null,
    val startDate: String? = null,
    val loan46: String? = null,
    val perc: String? = null,
    val creditType: String? = null,
    val recommendedAmount: String? = null,
    val currency: String? = null,
    val onOf: String? = null,
    var recommendedAmountForPayment: String? = null,
    var paymentAmount: String? = null,
    var earlyClosure: String? = null,
    var keep_future_percents: String? = "false",
    var saldo1: String? = "0",
    var saldo2: String? = "0",
    var saldo3: String? = "0",
    var saldo5: String? = "0",
    var saldo7: String? = "0",
    var saldo46: String? = "0",
    var saldo118: String? = "0",
    var saldo22: String? = "0",
    var saldo26: String = "0",
    var percDLO: String? = null,
    var overdraftLimit: String? = null,
    var percDLP: String? = null,
    var repaymentType: String? = null,
    val cardNumber: String? = null,
    var arrearDate: String? = null,
    var loanNumber: String? = null,
    var totalDebt: String? = null,
    var percOverLoanAmount: String? = null,
    var tRedempPerc: String? = null,
    var deadlineConfirmation: String? = null,
    var redemptionDay: String? = null,
    var lnMonth: Int? = null,
    var tRedempTotal: String? = null,
    var followPaySum: String? = null,
    var is_reacted: Int

) : Serializable